communication:
  auth:
    request-exchange: auth-request-exchange
    response-exchange: auth-response-exchange
    response-queue: auth-response-queue
  task:
    request-exchange: task-request-exchange
    response-exchange: task-response-exchange
    response-queue: task-response-queue