jwt:
  secret: k1opdcs23Kospos023dklsSD23ldsadpm23lasdDSamlxk
  expiration: 86400000s

communication:
  auth:
    request-queue: auth-request-queue
    request-exchange: auth-request-exchange
    response-exchange: auth-response-exchange